name: pull-request
on:
  push:
    paths:
      - 'management/**'
jobs:
  repo:
    name: Baixar codigo do git e cachear
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn clean compile