name: pull-request
on:
  push:
    branch: main
jobs:
  repo:
    name: Baixar codigo do git e cachear
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project with Maven
        env:
          ENV: test
          spring_profiles_active: test
        run: mvn package
